on:
  push:
    branches:
      - master
jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        service_account_email: ${{ secrets.EMAIL }}
        service_account_key: ${{ secrets.CREDENTIALS }}
        project_id: ${{ secrets.PROJECT_ID }}
        export_default_credentials: true
    
    - name: Deploy
      run: gcloud app deploy
      # run: gcloud run deploy
      # ${{ secrets.GCP_APPLICATION }}

